// 轮播图常量配置
export const CAROUSEL_CONFIG = {
  DEFAULT_HEIGHT: "500px",
  DEFAULT_BORDER_RADIUS: "16px",
  DEFAULT_COVERFLOW_ROTATE: 30,
  DEFAULT_COVERFLOW_DEPTH: 150,
  DEFAULT_COVERFLOW_STRETCH: 0,
  DEFAULT_COVERFLOW_MODIFIER: 1,
  DEFAULT_COVERFLOW_SLIDES_PER_VIEW: 2.2,
  TRANSITION_SPEED: 800,
  // 最少需要幻灯片数量，coverflow效果至少需要5张才能保证良好效果
  MIN_DUPLICATED_SLIDES: 6,
  // 不同效果的最少幻灯片数量
  MIN_SLIDES: {
    SLIDE: 3,
    FADE: 2,
    COVERFLOW: 5,
  },
};
